# Generated by Django 4.1 on 2022-11-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atividadesetapa3',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
