# Generated by Django 4.1 on 2022-11-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_alter_atividadesetapa1_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='descr',
            field=models.CharField(max_length=3800),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='descr',
            field=models.CharField(max_length=3800),
        ),
        migrations.AlterField(
            model_name='atividadesetapa3',
            name='descr',
            field=models.CharField(max_length=3800),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='descr',
            field=models.CharField(max_length=3800),
        ),
    ]
