# Generated by Django 4.1 on 2022-11-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_alter_atividadesetapa1_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=3800),
        ),
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='descrTemp',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='macro',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='tempo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa1',
            name='titleAtv',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=3800),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='descrTemp',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='macro',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='tempo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa2',
            name='titleAtv',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa3',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=3800),
        ),
        migrations.AlterField(
            model_name='atividadesetapa3',
            name='descrTemp',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa3',
            name='tempo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='atividadesetapa3',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='atividadesetapa3',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa3',
            name='titleAtv',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=3800),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='descrTemp',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='macro',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='tempo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='atividadesetapa4',
            name='titleAtv',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
