# Generated by Django 4.1 on 2022-11-12 21:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_alter_atividadesetapa1_descr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesEtapa',
            fields=[
                ('id_atividade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('tituloAtividade', models.CharField(blank=True, default='', max_length=500)),
                ('tipo', models.CharField(blank=True, default='', max_length=60)),
                ('descricao', models.CharField(blank=True, default='', max_length=3800)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('descricaoLink', models.CharField(blank=True, default='', max_length=500)),
                ('descricaoTempo', models.CharField(blank=True, default='', max_length=500)),
                ('tempoEstimado', models.IntegerField(blank=True, default=0)),
                ('sequencia', models.IntegerField(unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etada', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomeEtapa', models.CharField(blank=True, default='', max_length=60)),
                ('sequencia', models.IntegerField(unique=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Atividade', to='atividades.atividadesetapa')),
            ],
        ),
        migrations.CreateModel(
            name='SubAtividades',
            fields=[
                ('id_subAtividade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subAtividades', to='atividades.atividadesetapa')),
            ],
        ),
        migrations.DeleteModel(
            name='AtividadesEtapa1',
        ),
        migrations.DeleteModel(
            name='AtividadesEtapa2',
        ),
        migrations.DeleteModel(
            name='AtividadesEtapa3',
        ),
        migrations.DeleteModel(
            name='AtividadesEtapa4',
        ),
        migrations.AddField(
            model_name='atividadesetapa',
            name='etapaPertencente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapaPertencente', to='atividades.etapa'),
        ),
    ]
