# Generated by Django 4.1 on 2022-11-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_atividadesetapa_etapa_subatividades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='atividade',
        ),
    ]
